import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/antigravity_service.dart';
import '../services/session_tracker.dart';

/// ParentDashboard — the Progress Guardian interface.
/// Shows weekly report generated by the Progress Guardian agent,
/// plus a live stats summary from local session data.
/// Judges: this is where the "warm parent empowerment" story lives.
class ParentDashboard extends StatefulWidget {
  const ParentDashboard({super.key});

  @override
  State<ParentDashboard> createState() => _ParentDashboardState();
}

class _ParentDashboardState extends State<ParentDashboard> {
  late AntigravityService _agentService;
  late SessionTracker _tracker;

  String _report = '';
  bool _loading = false;
  bool _hasReport = false;

  @override
  void initState() {
    super.initState();
    _agentService = context.read<AntigravityService>();
    _tracker = context.read<SessionTracker>();
  }

  Future<void> _generateReport() async {
    setState(() {
      _loading = true;
      _report = '';
    });

    try {
      final report = await _agentService.generateWeeklyReport(
        _tracker.childId,
        childName: _tracker.childName,
        weekSummary: _tracker.buildWeekSummary(),
      );
      setState(() {
        _report = report;
        _hasReport = true;
        _loading = false;
      });
    } catch (e) {
      setState(() {
        _report =
            'Could not generate report right now. Please check your connection and try again.';
        _loading = false;
        _hasReport = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F7FF),
      appBar: AppBar(
        backgroundColor: const Color(0xFF6C63FF),
        foregroundColor: Colors.white,
        title: const Row(
          children: [
            Text('📊 ', style: TextStyle(fontSize: 20)),
            Text('Parent Dashboard',
                style:
                    TextStyle(fontWeight: FontWeight.bold, fontFamily: 'Nunito')),
          ],
        ),
        actions: [
          // Export trace JSON — for hackathon submission
          IconButton(
            icon: const Icon(Icons.download_outlined),
            tooltip: 'Export Agent Traces',
            onPressed: () {
              final json = _agentService.exportTracesAsJson();
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Trace JSON exported to console'),
                  backgroundColor: Color(0xFF6C63FF),
                ),
              );
              debugPrint('[TRACE EXPORT]\n$json');
            },
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ─── WEEK SUMMARY CARDS ─────────────────────────────────
            const Text(
              'This Week',
              style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w900,
                  color: Color(0xFF1A1040),
                  fontFamily: 'Nunito'),
            ),
            const SizedBox(height: 12),
            _buildStatCards(),
            const SizedBox(height: 10),
            _buildRetentionChips(),
            const SizedBox(height: 28),

            // ─── MODE COMPARISON ─────────────────────────────────────
            const Text(
              'Mode Comparison',
              style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w900,
                  color: Color(0xFF1A1040),
                  fontFamily: 'Nunito'),
            ),
            const SizedBox(height: 6),
            Text(
              'Toggle 🤖 AI / 📏 Rules in the game to build this comparison',
              style: TextStyle(fontSize: 12, color: Colors.grey[500]),
            ),
            const SizedBox(height: 12),
            _buildModeComparisonCard(),
            const SizedBox(height: 28),

            // ─── AGENT TRACE SUMMARY ────────────────────────────────
            const Text(
              'AI Adaptations Made',
              style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w900,
                  color: Color(0xFF1A1040),
                  fontFamily: 'Nunito'),
            ),
            const SizedBox(height: 12),
            _buildAdaptationList(),
            const SizedBox(height: 28),

            // ─── PROGRESS GUARDIAN REPORT ───────────────────────────
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Weekly Progress Report',
                  style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w900,
                      color: Color(0xFF1A1040),
                      fontFamily: 'Nunito'),
                ),
                // Agent badge
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: const Color(0xFF43C59E).withOpacity(0.12),
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                        color: const Color(0xFF43C59E).withOpacity(0.4)),
                  ),
                  child: const Row(
                    children: [
                      Icon(Icons.smart_toy_outlined,
                          size: 12, color: Color(0xFF43C59E)),
                      SizedBox(width: 4),
                      Text('Progress Guardian',
                          style: TextStyle(
                              fontSize: 10,
                              color: Color(0xFF43C59E),
                              fontWeight: FontWeight.bold)),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),

            if (!_hasReport && !_loading) ...[
              _buildGenerateCard(),
            ] else if (_loading) ...[
              _buildLoadingCard(),
            ] else ...[
              _buildReportCard(),
              const SizedBox(height: 16),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: _generateReport,
                  icon: const Icon(Icons.refresh_rounded),
                  label: const Text('Refresh Report'),
                  style: OutlinedButton.styleFrom(
                    foregroundColor: const Color(0xFF43C59E),
                    side: const BorderSide(color: Color(0xFF43C59E)),
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14)),
                  ),
                ),
              ),
            ],

            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildStatCards() {
    final traceCount = _agentService.traceLog.length;
    final adaptations = _agentService.traceLog
        .expand((t) => t.actions)
        .length;
    final rewards = _agentService.traceLog
        .expand((t) => t.actions)
        .where((a) => a.contains('reward'))
        .length;
    final categoryChanges = _agentService.traceLog
        .expand((t) => t.actions)
        .where((a) => a.contains('category'))
        .length;

    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      crossAxisSpacing: 12,
      mainAxisSpacing: 12,
      childAspectRatio: 1.6,
      children: [
        _StatCard(
            emoji: '🎮',
            value: '$traceCount',
            label: 'Sessions',
            color: const Color(0xFF6C63FF)),
        _StatCard(
            emoji: '🤖',
            value: '$adaptations',
            label: 'AI Actions',
            color: const Color(0xFF43C59E)),
        _StatCard(
            emoji: '⭐',
            value: '${_tracker.sessionScore}',
            label: 'Score',
            color: const Color(0xFFFFB800)),
        _StatCard(
            emoji: '🔥',
            value: '×${_tracker.bestStreak}',
            label: 'Best Streak',
            color: const Color(0xFFFF6584)),
      ],
    );
  }

  Widget _buildAdaptationList() {
    final entries = _agentService.traceLog.reversed.take(5).toList();

    if (entries.isEmpty) {
      return Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          border:
              Border.all(color: const Color(0xFF6C63FF).withOpacity(0.15)),
        ),
        child: const Center(
          child: Text(
            'No AI adaptations yet. Start a game session!',
            style: TextStyle(color: Colors.grey, fontSize: 14),
            textAlign: TextAlign.center,
          ),
        ),
      );
    }

    return Column(
      children: entries.map((entry) {
        final agentColor = entry.agent.contains('Therapy Director')
            ? const Color(0xFF6C63FF)
            : entry.agent.contains('Story Weaver')
                ? const Color(0xFFFF6584)
                : entry.agent.contains('Heuristic')
                    ? Colors.grey
                    : const Color(0xFF43C59E);
        return Container(
          margin: const EdgeInsets.only(bottom: 10),
          padding: const EdgeInsets.all(14),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(14),
            border: Border.all(color: agentColor.withOpacity(0.2)),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 36,
                height: 36,
                decoration: BoxDecoration(
                  color: agentColor.withOpacity(0.1),
                  shape: BoxShape.circle,
                ),
                child: Center(
                  child: Text(
                    entry.agent.contains('Therapy Director')
                        ? '🎯'
                        : entry.agent.contains('Story Weaver')
                            ? '📖'
                            : entry.agent.contains('Heuristic')
                                ? '📏'
                                : '📊',
                    style: const TextStyle(fontSize: 18),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Text(
                          entry.agent,
                          style: TextStyle(
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                              color: agentColor),
                        ),
                        const Spacer(),
                        Text(
                          _formatTime(entry.timestamp),
                          style: const TextStyle(
                              fontSize: 10, color: Colors.grey),
                        ),
                      ],
                    ),
                    const SizedBox(height: 4),
                    Text(
                      entry.reasoning.length > 100
                          ? '${entry.reasoning.substring(0, 100)}…'
                          : entry.reasoning,
                      style: const TextStyle(
                          fontSize: 12, color: Color(0xFF2D2060), height: 1.4),
                    ),
                    if (entry.actions.isNotEmpty) ...[
                      const SizedBox(height: 6),
                      Wrap(
                        spacing: 6,
                        children: entry.actions
                            .map((a) => Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 8, vertical: 2),
                                  decoration: BoxDecoration(
                                    color: agentColor.withOpacity(0.08),
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Text(a,
                                      style: TextStyle(
                                          fontSize: 10, color: agentColor)),
                                ))
                            .toList(),
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  Widget _buildGenerateCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(28),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            const Color(0xFF43C59E).withOpacity(0.08),
            const Color(0xFF6C63FF).withOpacity(0.05),
          ],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
            color: const Color(0xFF43C59E).withOpacity(0.25), width: 1.5),
      ),
      child: Column(
        children: [
          const Text('📝', style: TextStyle(fontSize: 48)),
          const SizedBox(height: 16),
          const Text(
            'Generate Weekly Report',
            style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w900,
                color: Color(0xFF1A1040),
                fontFamily: 'Nunito'),
          ),
          const SizedBox(height: 8),
          Text(
            'The Progress Guardian will create a warm, personalised report for your family.',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 14, color: Colors.grey[600], height: 1.5),
          ),
          const SizedBox(height: 24),
          SizedBox(
            width: double.infinity,
            height: 52,
            child: ElevatedButton.icon(
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF43C59E),
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(14)),
                textStyle: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    fontFamily: 'Nunito'),
              ),
              icon: const Icon(Icons.auto_awesome_rounded),
              label: const Text('Generate Report'),
              onPressed: _generateReport,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLoadingCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 40),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
            color: const Color(0xFF43C59E).withOpacity(0.2)),
      ),
      child: Column(
        children: [
          const CircularProgressIndicator(
            color: Color(0xFF43C59E),
          ),
          const SizedBox(height: 20),
          Text(
            'Progress Guardian is writing your report…',
            style: TextStyle(color: Colors.grey[600], fontSize: 14),
          ),
          const SizedBox(height: 4),
          const Text(
            'OBSERVE → INFER → WRITE',
            style: TextStyle(
                fontSize: 11,
                color: Color(0xFF43C59E),
                fontWeight: FontWeight.bold,
                letterSpacing: 1),
          ),
        ],
      ),
    );
  }

  Widget _buildReportCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF43C59E).withOpacity(0.1),
            blurRadius: 20,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Icon(Icons.auto_awesome_rounded,
                  color: Color(0xFF43C59E), size: 18),
              SizedBox(width: 8),
              Text(
                'Generated by Progress Guardian',
                style: TextStyle(
                    fontSize: 12,
                    color: Color(0xFF43C59E),
                    fontWeight: FontWeight.bold),
              ),
            ],
          ),
          const Divider(height: 24),
          Text(
            _report,
            style: const TextStyle(
                fontSize: 15, height: 1.7, color: Color(0xFF2D2060)),
          ),
        ],
      ),
    );
  }

  Widget _buildRetentionChips() {
    final retryPct = (_tracker.retryRate * 100).toStringAsFixed(0);
    final churnRisk = _tracker.isChurnRisk;
    final spikeAbandonment = _tracker.hasDifficultySpikeAbandonment;

    return Wrap(
      spacing: 8,
      children: [
        _Chip(
          label: 'Retry Rate $retryPct%',
          color: _tracker.retryRate > 0.5
              ? Colors.amber[700]!
              : const Color(0xFF43C59E),
          icon: Icons.refresh_rounded,
        ),
        _Chip(
          label: churnRisk ? 'Churn Risk' : 'Engaged',
          color: churnRisk ? Colors.red : const Color(0xFF43C59E),
          icon: churnRisk
              ? Icons.warning_amber_rounded
              : Icons.check_circle_outline,
        ),
        if (spikeAbandonment)
          _Chip(
            label: 'Spike Drop',
            color: Colors.orange,
            icon: Icons.trending_down_rounded,
          ),
      ],
    );
  }

  Widget _buildModeComparisonCard() {
    final agentSess = _agentService.agentSessions;
    final baseSess = _agentService.baselineSessions;
    final agentPct =
        (_agentService.agentAvgSuccess * 100).toStringAsFixed(0);
    final basePct =
        (_agentService.baselineAvgSuccess * 100).toStringAsFixed(0);
    final hasBoth = agentSess > 0 && baseSess > 0;
    final delta = hasBoth
        ? _agentService.agentAvgSuccess - _agentService.baselineAvgSuccess
        : null;

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF6C63FF).withOpacity(0.2)),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF6C63FF).withOpacity(0.06),
            blurRadius: 12,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Column(
        children: [
          _buildModeRow(
            emoji: '🤖',
            label: 'Antigravity Agent',
            sessions: agentSess,
            pct: agentPct,
            color: const Color(0xFF6C63FF),
          ),
          const Divider(height: 20),
          _buildModeRow(
            emoji: '📏',
            label: 'Fixed-Rule Heuristic',
            sessions: baseSess,
            pct: basePct,
            color: Colors.grey,
          ),
          if (delta != null) ...[
            const SizedBox(height: 14),
            Container(
              width: double.infinity,
              padding:
                  const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
              decoration: BoxDecoration(
                color: delta >= 0
                    ? const Color(0xFF43C59E).withOpacity(0.1)
                    : Colors.red.withOpacity(0.08),
                borderRadius: BorderRadius.circular(10),
              ),
              child: Text(
                delta >= 0
                    ? '${(delta * 100).toStringAsFixed(0)}% better success rate with Antigravity agents ✓'
                    : 'Run more AI sessions to build the comparison',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.bold,
                  color: delta >= 0 ? const Color(0xFF43C59E) : Colors.grey,
                ),
                textAlign: TextAlign.center,
              ),
            ),
          ] else ...[
            const SizedBox(height: 12),
            Text(
              'No data yet — toggle 🤖 AI / 📏 Rules in the game AppBar',
              style: TextStyle(fontSize: 12, color: Colors.grey[400]),
              textAlign: TextAlign.center,
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildModeRow({
    required String emoji,
    required String label,
    required int sessions,
    required String pct,
    required Color color,
  }) {
    return Row(
      children: [
        Text(emoji, style: const TextStyle(fontSize: 20)),
        const SizedBox(width: 10),
        Expanded(
          child: Text(label,
              style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.bold,
                  color: color)),
        ),
        Text('$sessions sessions',
            style: const TextStyle(fontSize: 11, color: Colors.grey)),
        const SizedBox(width: 10),
        Text('$pct%',
            style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w900,
                color: color,
                fontFamily: 'Nunito')),
      ],
    );
  }

  String _formatTime(DateTime dt) {
    final h = dt.hour.toString().padLeft(2, '0');
    final m = dt.minute.toString().padLeft(2, '0');
    return '$h:$m';
  }
}

class _StatCard extends StatelessWidget {
  final String emoji, value, label;
  final Color color;

  const _StatCard({
    required this.emoji,
    required this.value,
    required this.label,
    required this.color,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: color.withOpacity(0.2)),
        boxShadow: [
          BoxShadow(
            color: color.withOpacity(0.08),
            blurRadius: 12,
            offset: const Offset(0, 4),
          )
        ],
      ),
      child: Row(
        children: [
          Text(emoji, style: const TextStyle(fontSize: 28)),
          const SizedBox(width: 10),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(value,
                  style: TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.w900,
                      color: color,
                      fontFamily: 'Nunito')),
              Text(label,
                  style:
                      const TextStyle(fontSize: 11, color: Colors.grey)),
            ],
          ),
        ],
      ),
    );
  }
}

class _Chip extends StatelessWidget {
  final String label;
  final Color color;
  final IconData icon;

  const _Chip({required this.label, required this.color, required this.icon});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withOpacity(0.35)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 13, color: color),
          const SizedBox(width: 5),
          Text(label,
              style: TextStyle(
                  fontSize: 11, fontWeight: FontWeight.bold, color: color)),
        ],
      ),
    );
  }
}
